url: "https://pradhanojas.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/home" # the subpath of your site, e.g. /blog
title: "Ojas Pradhan" # the name of your site, e.g. ACME Corp.
description: "Building Science and Engineering Group | Drexel University"
