menu:
- {name: 'research', url: '/courses'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv/resume-pradhanojas.pdf'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/pradhanojas'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Ojas-Pradhan'}
- {icon: 'google-scholar', class: 'ai ai-google-scholar', link: 'https://scholar.google.com/citations?user=GCiV73sAAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/pradhanojas'}

contacts:
- {name: 'Ojas Pradhan', title: 'Curtis 153A', department: 'Drexel University', institution: '3141 Chestnut St., Philadelphia', institution_address: '', phone: '', email: 'omp28@drexel.edu', office: '', image: 'assets/img/contact.jpg'}
