menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

research:
- {name: 'Lagged kNN Approach for Data Imputation', url: 'data-imputation'}
- {name: 'DBN-based Fault Diagnosis Framework', url: 'fault-diagnosis'}
- {name: 'DBN-based Fault Prognosis Framework', url: 'fault-prognosis'}

social:
- {icon: 'github', link: 'https://github.com/pradhanojas'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/pradhanojas'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Ojas-Pradhan'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=GCiV73sAAAAJ&hl=en'}

contacts:
- {name: 'Ojas Pradhan', title: 'Curtis 153A', department: 'Drexel University', institution: '3141 Chestnut St., Philadelphia', institution_address: '', phone: '', email: 'omp28@drexel.edu', office: '', image: 'assets/img/contact.jpg'}
