menu:
- {name: 'home', url: ''}
- {name: 'skills', url: '/skills'}
- {name: 'publications', url: '/publications'}

social:
- {icon: 'github', link: 'https://github.com/pradhanojas'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/pradhanojas'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Ojas-Pradhan'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=GCiV73sAAAAJ&hl=en'}
